version: "3"
networks:
    test-automation-setup:
        external: true
services:
  chrome:
    image: selenium/node-chrome:4.0.0-beta-4-prerelease-20210517
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
        - test-automation-setup
  firefox:
    image: selenium/node-firefox:4.0.0-beta-4-prerelease-20210517
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
    - test-automation-setup   
  hub:
    image: selenium/hub:4.0.0-beta-4-prerelease-20210517
    container_name: hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
    - test-automation-setup
  mvn_tests: 
    build:
        context: .
        dockerfile: Dockerfile
    networks:
        - test-automation-setup
    entrypoint: mvn clean test -Dbrowser=chrome -DgridURL=selenium-hub:4444
